server:
  port: 8083
  servlet:
    context-path: /ui2
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false    # 我们禁用了default Basic Authentication
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token  # accessTokenUri 是获取访问令牌的URL
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize  # 是授权用户被重定向的目标URL
    resource:
      userInfoUri: http://localhost:8081/auth/user/me # 是用户终端访问用户信息的URL
spring:
  thymeleaf:
    cache: false